"""empty message

Revision ID: 5f2c2b034fe9
Revises: 8dba08eb26a3
Create Date: 2025-05-12 13:42:16.937440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2c2b034fe9'
down_revision = '8dba08eb26a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('appointment_time', sa.Time(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('consultation_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_date', sa.DATETIME(), nullable=True))
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('appointment_time')
        batch_op.drop_column('appointment_date')

    # ### end Alembic commands ###
